# The best option (in my opnion) however does not redeploy after configMap updates.
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-name-serverless-cm
  namespace: my-app-ns
data:
  # overrided by deployment env variable
  QUARKUS_APP_CUSTOM_MESSAGE: "Hello from <<CONFIG_MAP>>."
